repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.14.1
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline', '--disable-filter', 'detect_secrets.filters.heuristic.is_likely_id_string']
    exclude: '(pnpm-lock.yaml|poetry.lock)'
