version: "3.8"

networks:
  proxy:
    external: true

services:
  server:
    image: zwop:staging
    volumes:
      - ./config:/app/config
    env_file:
      - .env
    environment:
      - ZWOP_PROXY_ROOT=/zwop-staging
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.zwop-staging.stripprefix.forceSlash=false"
      - "traefik.http.middlewares.zwop-staging.stripprefix.prefixes=/zwop-staging"
      - "traefik.http.routers.zwop-staging.middlewares=zwop-staging"
      - "traefik.http.routers.zwop-staging.rule=Host(`exfldadev01.desy.de`) && PathPrefix(`/zwop-staging{slash:(\/|$)}`)"
      - "traefik.http.services.zwop-staging.loadbalancer.server.port=8000"
    command: ["poe", "staging"]
