name: zwop-staging

include:
  - compose.yml

networks:
  proxy:
    external: true

services:
  server:
    build: .
    environment:
      - "ZWOP_TOKEN_WRITER__ZWOP_URL=https://exfldadev01.desy.de/${COMPOSE_PROJECT_NAME}"
    networks:
      - proxy
    restart: unless-stopped