name: zwop-dev

services:
  server:
    environment:
      - "ZWOP_TWS__ZWOP_URL=http://localhost:8000/${COMPOSE_PROJECT_NAME}"
      - "ZWOP_TWS__URL=https://tws:8443/"
      - "ZWOP_ADDRESS=http://0.0.0.0:8000"

  tws:
    build:
      context: .
      target: zwop-tws
    volumes:
      - ./certs:/app/certs
    env_file:
      - .env

  traefik:
    image: "traefik:latest"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8000"
      - "--log.level=DEBUG"
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathRegexp(`^/whoami(/|$)`)"
