version: "3.8"

networks:
  proxy:
    external: true

services:
  zwop-staging:
    build: .
    volumes:
      - ./config:/app/config
    env_file:
      - .env
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.middlewares.zwop-staging.stripprefix.forceSlash: false
      traefik.http.middlewares.zwop-staging.stripprefix.prefixes: /zwop-staging
      traefik.http.routers.zwop-staging.middlewares: zwop-staging
      traefik.http.routers.zwop-staging.rule: PathPrefix(`/zwop-staging`)
      traefik.http.services.zwop-staging.loadbalancer.server.port: 8000
    command: ["poe", "staging"]
