networks:
  proxy:
    external: true

services:
  server:
    image: ${IMAGE:-ghcr.io/european-xfel/zulip-write-only-proxy}:${TAG:?error}
    volumes:
      - ./config:/config
    env_file:
      - .env
    environment:
      - ZWOP_PROXY_ROOT=/${PATH_PREFIX:-zwop}
      - ZWOP_PROXY_HEADERS=true
      - ZWOP_FORWARDED_ALLOW_IPS=*
      - ZWOP_TOKEN_WRITER__ZWOP_URL=https://${HOST:-exfldadev01.desy.de}/${PATH_PREFIX:-zwop}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.zwop-stripprefix.stripprefix.prefixes=/${PATH_PREFIX:-zwop}"
      - "traefik.http.routers.zwop.middlewares=zwop-stripprefix"
      - "traefik.http.routers.zwop.rule=Host(`${HOST:-exfldadev01.desy.de}`) && PathPrefix(`/${PATH_PREFIX:-zwop}{slash:(/|$)}`)"
      - "traefik.http.services.zwop.loadbalancer.server.port=8000"
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
        monitor: 10s
        max_failure_ratio: 0
      restart_policy:
        condition: any
        delay: 5s
        window: 120s