version: "3.8"

services:

  zwop:
    image: ghcr.io/robertrosca/zulip-write-only-proxy:feat-initial-dev
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
        monitor: 5s
        max_failure_ratio: 0
    volumes:
      - ./config:/app/config

  nginx:
    image: nginx:1.25.1
    ports:
      - ${PORT:?err}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
