---
version: 3

tasks:
  css:
    cmds:
      - |
        pnpm exec tailwindcss \
          -o src/zulip_write_only_proxy/frontend/static/main.css
    sources:
      - src/**/*.html
      - ./tailwind.config.js
    generates:
      - src/zulip_write_only_proxy/frontend/static/main.css

  css-watch: |
    pnpm exec tailwindcss \
      -o src/zulip_write_only_proxy/frontend/static/main.css \
      --watch

  htmx: |
    cd ./src/zulip_write_only_proxy/frontend/static && \
      wget -N https://unpkg.com/htmx.org@1.9.10/dist/htmx.js

  poe-up: poe up

  dev:
    deps: [css-watch, htmx, poe-up]

  docker: docker compose -p zwop-dev -f ./compose.yml up --build --watch

  staging:
    dotenv: ['.env']
    cmds:
      - docker build . --tag zwop:staging
      - docker compose -p zwop-staging -f ./compose.staging.yml up -d

  prod:
    dotenv: ['.env']
    cmds:
      - docker compose -p zwop -f ./compose.prod.yml up -d
