name: Setup Step

description: |
  This step sets up Python and Poetry, and caches the virtual environment.
  It is intended to be used as a step in a workflow that runs Python code.

inputs:
  python-version:
    required: true
    description: "Python version to use with `actions/setup-python`"

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip poetry
        poetry self add "poetry-dynamic-versioning[plugin]"
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local

    - name: Use venv cache
      uses: actions/cache@v3
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}-${{ inputs.python-version }}

    - name: Install project
      shell: bash
      run: |
        poetry --no-ansi --no-interaction install
