name: Lint

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip poetry
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Use venv cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}-${{ matrix.python-version }}

      - name: Install project
        run: |
          poetry --no-ansi --no-interaction install

      - name: Lint - ruff
        if: always()
        run: poetry run poe ruff

      - name: Lint - black
        if: always()
        run: poetry run poe black --check

      - name: Lint - mypy
        if: always()
        run: poetry run poe mypy

      - name: Lint - pyright
        if: always()
        run: poetry run poe pyright
