name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - uses: ./.github/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test
        run: poetry run poe test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-image:
    needs: test
    uses: ./.github/workflows/build-image.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit
